name: 'asta'
description: 'Test a web application with ASTA'

inputs:
    pat:
        description: |
            A Personal Access Token (PAT) used to authenticate the run.
        required: true

    variantId:
        description: 'The ID or name of the application variant to test'
        required: true

    parameters:
        description: 'Run template ID (string) or custom parameters (YAML/JSON)'
        required: true

    repositoryUrl:
        description: 'ASTA repository base URL'
        required: false
        default: 'https://sqabot.ai'

    expectFailure:
        description: 'Set to true if the test is expected to fail'
        required: false
        default: 'false'

outputs:
    run-id:
        description: The unique ID of the ASTA test run

runs:
    using: 'node20'
    main: 'dist/index.js'
